### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by manzt** [manzt/anndata-repr#20]
- [x] Adjust SVG representation #21 
  - Start from variant2 SVG
  - No stacking of layers, obs, var (redundant information)
  - Prefer styles from variant 1 (no rounding, correct colors)
  - No table on the side (but think about what we can put there)
  - Remove redundant dims for obsp/varm
- [x] Use row-oriented layout for data frames (obs/var) #21 
- [x] Add search box #22 
  - inspiration from https://github.com/benbovy/xarray-fancy-repr
  - expand collapsible sections and filter fields by search
- [ ] Add X within layers collapsible section (separate from layers)
- [ ] Make uns section recursive (how many levels?) and inherit `__repr_html__ `
- [ ] More info in the preview (when it’s collapsed)
- [ ] Test in docs
- [ ] Add repr configuration to the top of the notebook
- [ ] Check xarray file, see if we changed things
- [ ] **Finally**: publish to PyPI and contact scverse folks on zulip to advertise
